### ISSUE TITLE
Feature Request: Add Ability to Download Videos Over a Date Range

### ISSUE THREAD

**Issue by alessiozanutta** [JurajNyiri/pytapo#108]
I'm using your script for downloading videos from my c220, and it's been incredibly helpful. 

Currently, the script allows for downloading videos by specifying a single date.
I'd like to propose a feature enhancement that would significantly increase the script's flexibility and user convenience. It would be great if we could specify not just a single day but a range of dates, such as a week, to download videos from multiple days in one go.

This feature would be particularly useful for users who need to review footage over a specific period without the need to initiate multiple download sessions and have the possibility to sync recorded files into a specific folder.

Thank you for considering this request. I believe it would make a great addition to your already excellent script.

**Comment by JurajNyiri** [comment]
This is just an example on how to get started, feel free to write your own script around it.
