### ISSUE TITLE
Setup documentation on RTD

### ISSUE THREAD

**Issue by germainlefebvre4** [JurajNyiri/pytapo#112]
What about setting up the librarie documentation on ReadTheDocs?

I have done the same for libtado at https://libtado.readthedocs.io/en/latest/

**Comment by JurajNyiri** [comment]
No thank you, documentation is in github for now, I do not have enough time to maintain that.

**Comment by germainlefebvre4** [comment]
What about my help on this side? Setup, CI, content, etc
