### ISSUE TITLE
[Feature] Download saved clips

### ISSUE THREAD

**Issue by quidnu** [JurajNyiri/pytapo#118]
On C210 there is a way to save clips, I would like to back those up to my computer. Is there a way to download saved clips?

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/pytapo?tab=readme-ov-file#downloading-recordings

**Comment by quidnu** [comment]
I have continuous recording turned on so that script downloads the entire day. What I'm looking for is the ability to download clips that are explicitly saved using, for example, the tapo iOS "download" function on a clip with detected motion. When you use this feature there is a message that the clip is "downloaded to camera", I would like to retrieve these clips to store them on my computer.
