### ISSUE TITLE
Is there a way to play the audio file we created on the tapo camera's speaker?

### ISSUE THREAD

**Issue by tongticktack** [JurajNyiri/pytapo#14]
Hi, I am trying to use Tapo c200 camera to play audio file whenever we want. I see that function which triggers alarm when noise detected but I cant find a way to play the audio file we created. Thank you!

**Comment by JurajNyiri** [comment]
Hey, how can you do this via an app?

**Comment by tongticktack** [comment]
I use TP-Link Tapo application but as far as I know there is no way to use application to achieve what I want. But I assume your project can do such thing
![image](https://user-images.githubusercontent.com/43903902/111861614-0f9bd200-8993-11eb-9fb4-c46dea3349dc.png)

**Comment by JurajNyiri** [comment]
Unfortunately currently it cannot.
