### ISSUE TITLE
moveMotorStep and angle

### ISSUE THREAD

**Issue by rajil** [JurajNyiri/pytapo#15]
The Tapo C200 accepts both horizontal and vertical angle as this picture shows. The moveMotorStep function accepts only a single value of angle (0-360), how can i position the camera at a particular horizontal/vertical angle?

![tapo](https://static.tp-link.com/Tapo-C200_EU_1.0_1908_English_02_normal_1568705572953e.png)

**Comment by JurajNyiri** [comment]
Use moveMotor function. Example: https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/custom_components/tapo_control/camera.py#L298
