### ISSUE TITLE
Dump entire Json data

### ISSUE THREAD

**Issue by calvinwynne** [JurajNyiri/pytapo#16]
Is there a way to get the entire JSON data?

![image](https://user-images.githubusercontent.com/32861276/116788714-cb8b0980-aac8-11eb-8ce1-bbb2efe076c5.png)
 
I want to set simultaneous to True and adjust the motor speed.

This got me to wonder what other parameters are available for us to modify
Thanks for this amazing repo

**Comment by JurajNyiri** [comment]
Data are returned from camera by executing functions in its API.

Check out all the get functions inside this library to see what is available. There might be more that has not been discovered yet.

**Comment by calvinwynne** [comment]
Thank You for your quick reply. I'll surely check it out. I was hoping I could somehow dump all the data as shown in this image
![image](https://user-images.githubusercontent.com/32861276/116792148-883a9600-aadc-11eb-9cb8-72bb8de4e1a7.png)
https://drmnsamoliu.github.io/userconfig.html
