### ISSUE TITLE
Camera doesn't auto track target no more

### ISSUE THREAD

**Issue by Doctor0sama** [JurajNyiri/pytapo#17]
Hey, the auto track target function was working greatly with very high accuracy. But since the new update (1.1.7) it doesn't do that anymore and the camera stays still unless I move it.

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/3.3.1w
![image](https://user-images.githubusercontent.com/5785999/117281795-50c54400-ae64-11eb-94b5-65262d7fe778.png)

**Comment by amahlaka** [comment]
Tested with an active Tapo Care subscription, setting the tracking mode with the api  does work again
