### ISSUE TITLE
Add more request for states ?

### ISSUE THREAD

**Issue by noenic** [JurajNyiri/pytapo#18]
Is it possible to add requests for states ? 
like :
             getPosition() wich return x and y coordonates
             getNightMode() wich return True if night mode is enable
             getMotionState() wich return True if the motion sensors is trigered

 thanks

**Comment by JurajNyiri** [comment]
there are no such functions publicly available yet
motion sensor in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control is achieved by using onvif
