### ISSUE TITLE
Unable to move motor on Tapo C210

### ISSUE THREAD

**Issue by Phyks** [JurajNyiri/pytapo#22]
Hi,

I'm trying to control my Tapo C210 with pytapo. Everything works fine so far, except for the motor control (pan and/or tilt).

When using

```python
tapo = Tapo(host, user, password)
tapo.moveMotorStep(10)
```

I get the following traceback:

```python
Traceback (most recent call last):
  File "/tmp/tapo/test.py", line 27, in <module>
    toggle_privacy()
  File "/tmp/tapo/test.py", line 18, in toggle_privacy
    tapo.moveMotorStep(10)
  File "/tmp/tapo/.venv/lib/python3.9/site-packages/pytapo/__init__.py", line 288, in moveMotorStep
    return self.performRequest(
  File "/tmp/tapo/.venv/lib/python3.9/site-packages/pytapo/__init__.py", line 113, in performRequest
    raise Exception(
Exception: Error: -64316 Response:{"error_code": -64316}
```

Thanks!
Best

**Comment by JurajNyiri** [comment]
Is your privacy mode turned on? If yes, you need to turn it off.

**Comment by Phyks** [comment]
Indeed, part of the issue was having privacy mode on. This is not enough still and the issue persists.

I discovered that `moveMotorStep` does not work while `moveMotor` does work.

So, here is snippet in case it might be useful to others to turn around the camera while switching to privacy mode, which is definitely a feature missing from original Tapo app IMO. 


```python
def get_privacy_mode(tapo):
    return tapo.getPrivacyMode().get('enabled', 'off') == 'on'


def toggle_privacy(tapo):
    current_privacy = get_privacy_mode(tapo)
    # Note: moving is disabled when in privacy mode.
    if current_privacy:
        tapo.setPrivacyMode(False)
        # Wait for privacy mode to be off, while avoiding infinite loop is the camera is stuck for some reason.
        for i in range(MAX_ITERATIONS):
            current_privacy = get_privacy_mode(tapo)
            if not current_privacy:
                break
            time.sleep(0.2)
            raise Exception('Tapo stuck in privacy mode!')
        tapo.moveMotor(-180, 0)
    else:
        tapo.moveMotor(180, 0)
        time.sleep(10)
        # TODO: Check if Tapo is moving
        tapo.setPrivacyMode(True)
```

@JurajNyiri are you aware of any mean to check that the camera is not moving? (see TODO) This is the only bit remaining in the snippet and it would definitely be better than a timeout :/

I thought about `tapo.getMotorCapability()`, but it only returns constant values, not the current positions.

**Comment by JurajNyiri** [comment]
Some cameras can be moved by moveMotor and some with moveMotorStep, this is expected.

AFAIK there is no function to discover moving state of the camera.
