### ISSUE TITLE
SetSystemDateAndTime

### ISSUE THREAD

**Issue by alecks68** [JurajNyiri/pytapo#25]
I am using a C310 without HA. I managed to do settings via pytapo and reading events through onvif-zeep-async (see https://github.com/pablo-zarate/Tapo-C200-event-listener). 
However I am not able to manage SetSystemDateAndTime via onvif. I tried the onvif-zeep-async and onvif-zeep with python3 and onvif with python2. In python3 I am stuck with errors on wsdl and xml. In pyhton2 I end up with 
onvif.exceptions.ONVIFError: Type not found: 'tt:AutoRebootSupport'

Is there any support on setting the time through pytapo or any recommendation for a simple onvif library or commandline tool to do the job?

**Comment by JurajNyiri** [comment]
Hello, see https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/custom_components/tapo_control/utils.py#L197 . That method is being called periodically to sync time in the integration.

**Comment by alecks68** [comment]
Hi, thanks for the link, but I am not using HA. I am looking for a stand-alone library or tool to run device_mgmt.SetSystemDateAndTime(time_params). I had no luck with the python libraries mentioned in my initial post. I am just wondering if you know of anything simple.

**Comment by JurajNyiri** [comment]
Hey, the code I linked above, specifically the function I linked is doing exactly what you need, and in python. You can probably copy and adjust the code. I do not know of any tool that like that.

**Comment by alecks68** [comment]
Just if anyone else is struggling with this. I got it running with onvif for python2 on raspberry pi.

The type AutoRebootSupport is not defined. 
```onvif.exceptions.ONVIFError: Type not found: 'tt:AutoRebootSupport'```
I guess this is something missing in onvif.xsd. As I have no experience in wsdl nor xml, my "dirty" workaround to this is following change in /usr/local/lib/python2.7/dist-packages/onvif/client.py

```
##  capabilities = self.devicemgmt.GetCapabilities({'Category': 'All'})
capabilities = self.devicemgmt.GetCapabilities({'Category': 'Events'})
```

Then, a simple python program as  commented by @JurajNyiri works fine for me.
```
#!/usr/bin/python2
import datetime
import time
from onvif import ONVIFCamera

user = "xxx"
password = "yyy"
host = "192.168.a.b"

mycam = ONVIFCamera(host,2020,user,password)

#set_time once a day via cron job via Raspi
time_request = mycam.devicemgmt.create_type('SetSystemDateAndTime')
time_request.DateTimeType = "Manual"
time_request.DaylightSavings = True
now = datetime.datetime.utcnow()
time_request.UTCDateTime = {
            "Date": {"Year": now.year, "Month": now.month, "Day": now.day},
            "Time": {
                "Hour": now.hour if time.localtime().tm_isdst == 0 else now.hour + 1,
                "Minute": now.minute,
                "Second": now.second,
            },
        }
mycam.devicemgmt.SetSystemDateAndTime(time_request)
```
