### ISSUE TITLE
Notify

### ISSUE THREAD

**Issue by lamerjack** [JurajNyiri/pytapo#29]
Is possible, or it will be possible in future to enable and disable Notifications?
I want to use tapo camera as alarm.
But i want to disable when i'm at home (and i have manually disable on all cameras when i'm at home)
Anyway very nice software thanks!

**Comment by JurajNyiri** [comment]
Notifications are cloud based, so it will not be supported in this library.

What you want is possible (and much more) via Home Assistant and its plugin https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/ .
