### ISSUE TITLE
Unable to turn off Privacy mode (delete please)

### ISSUE THREAD

**Issue by WattageGuy** [JurajNyiri/pytapo#33]
Im using following code:

```
from pytapo import Tapo

user = "xxxx" # user you set in Advanced Settings -> Camera Account
password = "xxx" # password you set in Advanced Settings -> Camera Account
host = "192.168.xxx.xxx" # ip of the camera, example: 192.168.1.52

tapo = Tapo(host, user, password)

print(tapo.getPrivacyMode())

print(tapo.setPrivacyMode('enabled'))

print(tapo.getPrivacyMode())
```

And this is my output:
`{'.name': 'lens_mask_info', '.type': 'lens_mask_info', 'enabled': 'on'}
{'result': {'responses': []}, 'error_code': 0}
{'.name': 'lens_mask_info', '.type': 'lens_mask_info', 'enabled': 'on'}`

It wont disable. Why?

**Update: Realised I needed to leave string empty. Thought sending enabled would turn it off if it was enabled (act as switch)**

`print(tapo.setPrivacyMode(''))`

**Please delete this issue!**

**Comment by JurajNyiri** [comment]
It is accepting boolean parameter.

**Comment by WattageGuy** [comment]
Thanks!
