### ISSUE TITLE
Set time/date

### ISSUE THREAD

**Issue by WattageGuy** [JurajNyiri/pytapo#34]
As titles says. Is their any way to change date and time of tapo cameras. Im blocking my cameras from internet and only using them via HomeKit intergration (Scrypted) but when doing this the camera date is always 2021-12-02. I guess it's because blocking internet access block any NTP server cameras are using. So any way to set NTP server or add date manually?

**Comment by JurajNyiri** [comment]
Yes you can use onvif to set date or time. You can check home assistant integration which has this functionality built in.

**Comment by WattageGuy** [comment]
Unfortunately my camera c100 do not have any time/date option with HA onvif thats why I was asking here

**Comment by JurajNyiri** [comment]
Hello, I meant this integration https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/

**Comment by WattageGuy** [comment]
I've been using this integration for a couple of days for the motion feature. But it haven't changed/synchronised time. But here you said that you would be able to implement manuell sync: https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/119 , is it available? And what do you mean by onvif standard, do you mean onvif profile?

**Comment by WattageGuy** [comment]
Okay I solved it. I need to reload the plugin in order for the camera to get right time. Guess I need to setup an automation that makes it reload once a day until you implemented the manual way. But thanks for the help and for making this plugin. 😃
