### ISSUE TITLE
Get and Set Home / Away Modes?

### ISSUE THREAD

**Issue by Ultrabenosaurus** [JurajNyiri/pytapo#36]
I can see a previous issue asking about toggling notifications, which is not possible due to being a cloud feature. The Android app also has Home / Away modes where you can set different settings for one or more cameras and it applies them to each camera individually (there's even a progress pop-up counting up until all selected devices are updated). 

I have to ask even though it is 99% sure a cloud feature as well, but is it possible to get and set this from Python instead of toggling notifications directly?

I just can't believe the Tapo app still doesn't have geofencing to automate this stuff... It's literally called Home / Away Mode but doesn't actually check if you're home or away, you have to manually open the app and tap a button...

**Comment by JurajNyiri** [comment]
Home and away modes just execute multiple actions you set up automatically. You can achieve the same and a lot more via home assistant and tapo integration. Or you can write your own script that would execute the same functions.
