### ISSUE TITLE
Unable to turn off Privacy mode too

### ISSUE THREAD

**Issue by zazDuTuitisme** [JurajNyiri/pytapo#39]
Hi,

I'm using the following code :

```
    tapo=Tapo(host, user, password)
    tapo.setPrivacyMode(False)
```
 

And I also try the methode given in #33 but it isn't worked for me...

The activated part works as well :

`tapo2.setPrivacyMode(True)`

Any help ?

Thanks

**Comment by robozb** [comment]
Dear @zazDuTuitisme,

What kind of model did You access with the library? I can't connect to my Tapo C110 :(

Thanks: Bela
