### ISSUE TITLE
Add ability to send audio to camera

### ISSUE THREAD

**Issue by JurajNyiri** [JurajNyiri/pytapo#41]
I started experimenting with sending audio to the camera, ideally in the future to start use it as media_player device in Home Assistant, basically having ability to play any mp3.

Branch [talk_experiments](https://github.com/JurajNyiri/pytapo/tree/talk_experiments)
Test file:

```
from pytapo import Tapo
import json
import asyncio
import logging

logging.basicConfig(level=logging.DEBUG)
# change variables here
host = ""  # change to camera IP
user = ""  # your username
password = ""  # your password
password_cloud = ""  # set to your cloud password

tapo = Tapo(host, user, password, password_cloud)

devID = tapo.getBasicInfo()["device_info"]["basic_info"]["dev_id"]


async def download_async():
    print("Starting...")
    mediaSession = tapo.getMediaSession()
    async with mediaSession:
        payload2 = {
            "params": {"talk": {"deviceId": devID, "mode": "aec"}, "method": "get"},
            "type": "request",
        }

        payload = json.dumps(payload2)
        output = b""
        dataChunks = 0

        print("Opened session")
        async for resp in mediaSession.transceive(payload):
            if resp.mimetype == "video/mp2t":
                # if len(resp.plaintext) != 376:
                dataChunks += 1
            else:
                # print(resp.plaintext)
                pass

            # if dataChunks > 2000:
            #    break

        fileName = "./output/stream.ts"
        print("Saving to " + fileName + "...")
        file = open(fileName, "wb")
        file.write(output)
        file.close()


loop = asyncio.get_event_loop()
loop.run_until_complete(download_async())
```

The [main part](https://github.com/JurajNyiri/pytapo/blob/talk_experiments/pytapo/media_stream/session.py#L496) is currently trying to open a working mp2 file, read first 1520 bytes (the same size as tapo is sending payloads in) and send it to the camera.

Unfortunately, nothing happens.

**Comment by AlexxIT** [comment]
I don't know if FFmpeg able to generate properly TS file for Tapo cameras. Because they using not popular codec for this container:

https://github.com/AlexxIT/go2rtc#source-tapo
https://github.com/AlexxIT/go2rtc#stream-to-camera

**Comment by JurajNyiri** [comment]
Thank you, I am looking into this, it looks really great!

**Comment by JurajNyiri** [comment]
I do not plan to implement this feature as it was already done very well inside https://github.com/AlexxIT/WebRTC#stream-to-camera and https://github.com/AlexxIT/go2rtc#stream-to-camera.

**Comment by greta-thunberg** [comment]
its a funny coincidence during the weekend I also tried to decompile the official tapo app to get the audio backchannel :zany_face: 

if you are interested, here are the extracted java classes that produce the mp2t stream [https://gitlab.com/Gretulililinka/TapoTalk/-/tree/master/java_src](https://gitlab.com/Gretulililinka/TapoTalk/-/tree/master/java_src)

and proof thats working [https://gitlab.com/Gretulililinka/TapoTalk/-/tree/master/](https://gitlab.com/Gretulililinka/TapoTalk/-/tree/master/)

blog ( czech lang :czech_republic: )about how I found it  [https://www.abclinuxu.cz/blog/GretinBlogisek/2023/2/tapovoko-129535-128226](https://www.abclinuxu.cz/blog/GretinBlogisek/2023/2/tapovoko-129535-128226)

**Comment by Boteium** [comment]
Is go2rtc's stream-to-camera working on your devices ?
I've tried go2rtc and back channel audio either doesn't work at all or crash my camera (cause a reboot).

**Comment by JurajNyiri** [comment]
@Boteium intermittently for me, usually it does after a camera reboot. Please open issue in go2rtc repo.
