### ISSUE TITLE
Is it possible to use this library to get the camera image?

### ISSUE THREAD

**Issue by guilhermecgs** [JurajNyiri/pytapo#43]
Currently, I am using RTSP protocol to get images (png) (using opencv) from tapo cameras.

However, RTSP protocol somehow provides not good enough image resolution. (Not sure why)

So, is there a way (using this library) to get camera "printscreens" with better resolution?

**Comment by JurajNyiri** [comment]
Not possible, even camera makes pictures from the video stream.
