### ISSUE TITLE
Update time

### ISSUE THREAD

**Issue by moritzgloeckl** [JurajNyiri/pytapo#5]
Hi,

to enhance the privacy of the camera I've disabled its Internet access capabilities through a firewall rule on my router.

Now I've noticed that the camera seems very bad at keeping the current time, in two weeks its already off by half a day.

So it would be good to have functionality to update the time on the camera/setting the appropriate NTP servers.

If I have time I will take a look to see if that's possible somehow.

Thanks,
Moritz

**Comment by JurajNyiri** [comment]
It's not possible via the app so it's not unfortunately possible at all. What you can do is set up your own ntp server and DNS and set the ntp used by the camera to your ntp server.

**Comment by moritzgloeckl** [comment]
Indeed it seems to be the case that you cannot set the time via the app (time-zones are configurable though, so I thought it must be possible to setup the time).

What I ended up doing now was giving the camera access to the internet on port 123 (the NTP port) for 5 minutes each day, which seems to be enough for it to query the current time. Working fine so far.
