### ISSUE TITLE
Downloading recordings on Windows

### ISSUE THREAD

**Issue by konrad-ch** [JurajNyiri/pytapo#50]
Hello, did anyone tried to download recordings on Windows machine? I'm getting the following error:
```
Downloading C:\[path]...
could not convert string to float: b''
Warning: Could not calculate length from stream.
```
On Ubuntu it works fine.

**Comment by JurajNyiri** [comment]
Make sure you have ffprobe and ffmpeg installed.

**Comment by konrad-ch** [comment]
> Make sure you have ffprobe and ffmpeg installed.

I have. ffmpeg+ffprobe 5.1.2
