### ISSUE TITLE
Add patrol mode

### ISSUE THREAD

**Issue by ThePrincelle** [JurajNyiri/pytapo#53]
Hi, 
Thanks for your work on this library.
I'm using it with my C210 camera and I was wondering if it was possible to control the "patrol" capability. 

There are two options: "Horizontal" and "Vertical".

Here's a capture of the app (In French ^^') :
![image](https://user-images.githubusercontent.com/52919205/229367826-5eb1dc61-e8c5-462a-bce9-bfa09991122f.jpeg)

Thanks for your response,
Maxime

**Comment by JurajNyiri** [comment]
Hey! I can add this once someone documents what is the HTTP call that goes out when the buttons are hit.

**Comment by AndreiArdelean1** [comment]
For horizontal patrol:
`{"method":"multipleRequest","params":{"requests":[{"method":"cruiseMove","params":{"motor":{"cruise":{"coord":"x"}}}}]}}`

**Comment by JurajNyiri** [comment]
@AndreiArdelean1 thank you, could you please also check what is the command to stop it?

**Comment by JurajNyiri** [comment]
Thank you! Have you found any command that gets the current state of cruise?

**Comment by AndreiArdelean1** [comment]
maybe: `{"method":"multipleRequest","params":{"requests":[{"method":"getPatrolAction","params":{"patrol":{"get_patrol_action":{}}}}]}}`

**Comment by JurajNyiri** [comment]
All works for me except the `getPatrolAction`, I am getting -40210 which means the function is not supported/exists on my camera. Is there any other call? App somehow knows if the camera is cruising or not.

**Comment by AndreiArdelean1** [comment]
My best guess, for now, is something like https://md.depau.eu/s/r1Ys_oWoP#Live-streaming is used to send events to the app. I didn't notice any requests being made except the one to start patrol. I'm trying to test the stream in the link, but didn't manage to get it working (in Postman).

**Comment by JurajNyiri** [comment]
@AndreiArdelean1 now released in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.1.0.beta.1.
