### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by peakpeak-github** [JurajNyiri/pytapo#62]
Using the example code with camera C320WS:

from pytapo import Tapo

user = "user@xmail.com" # user you set in Advanced Settings -> Camera Account
password = "passWord" # password you set in Advanced Settings -> Camera Account
host = "192.168.9.102" # ip of the camera, example: 192.168.1.52

tapo = Tapo(host, user, password)

print(tapo.getBasicInfo())

**File "C:\Python311\Lib\site-packages\pytapo\\_ _init_ _.py", line 88, in refreshStok 
    raise Exception("Invalid authentication data")
Exception: Invalid authentication data**

Does camera C320WS have a different authentication scheme?
The camera works ok with the TP-Link app!

**Comment by JurajNyiri** [comment]
Yes, use `admin` and your cloud password.

**Comment by peakpeak-github** [comment]
Thanks!
