### ISSUE TITLE
Downloading Recordings

### ISSUE THREAD

**Issue by peakpeak-github** [JurajNyiri/pytapo#63]
Why do I need the Tapo cloud account password as I don't even use that service?
Downloading from the SD card on the phone works ok.

**Comment by JurajNyiri** [comment]
Because the camera requires access to admin account to access some functionalities which uses your cloud password.

**Comment by peakpeak-github** [comment]
Please elaborate: I do not have a cloud password, neither has the phone!

**Comment by JurajNyiri** [comment]
You do, its the password for your tplink account which you use to sign in into the app.

**Comment by peakpeak-github** [comment]
Ok, why do you call it the cloud password then?

**Comment by JurajNyiri** [comment]
There are two passwords, one you create for 3rd party account - local, where you provide account name and password. And another one for "admin" internal account, which uses your tplink **cloud** password. 
One is local, one is cloud (as in, your cloud account with tplink). It is named correctly.

**Comment by peakpeak-github** [comment]
Ok. I have one TP-link account with email and password where I can log in to the TP-link portal and also in the app for the camera. The 'admin' account uses the same password so executing
_tapo = Tapo(host, 'admin', password)
print(tapo.getBasicInfo())_
works ok.
However, executing
_password_cloud = password
user = 'admin'
tapo = Tapo(host, user, password_cloud, password_cloud)_
yields
**File "C:\Python311\Lib\site-packages\pytapo\__init__.py", line 88, in refreshStok
    raise Exception("Invalid authentication data")**
... and executing:
_password_cloud = password
user = 'emailaccount@domain.com' # Same user as in the app
tapo = Tapo(host, user, password_cloud, password_cloud)_
also yields
**File "C:\Python311\Lib\site-packages\pytapo\__init__.py", line 88, in refreshStok
    raise Exception("Invalid authentication data")**

What am I doing wrong here?

**Comment by peakpeak-github** [comment]
Yes, I was supposing that the tapo care subscription was the same as 'cloud'. Thanks for explaining that.
I can contact the camera through python and there are three videos and one still picture on the SD card.
However I get this error when executing the code to fetch content from the SD card:
**File "C:\Python311\Lib\site-packages\pytapo\__init__.py", line 138, in executeFunction
    raise Exception(
Exception: Error: -71112, Response: {"method": "searchVideoOfDay", "result": {}, "error_code": -71112}**

What am I doing wrong?
