### ISSUE TITLE
Error Code -71112 on download of recordings

### ISSUE THREAD

**Issue by peakpeak-github** [JurajNyiri/pytapo#64]
I can contact the camera through python and successfully run:
tapo = Tapo(host, user, password)
print(tapo.getBasicInfo())

Now trying to download content from the SD card. There are three videos and one still picture on the SD card which I can download through the phone app.
However I get this error when executing the example code to fetch content from the SD card:
File "C:\Python311\Lib\site-packages\pytapo\_init_.py", line 138, in executeFunction
raise Exception(
Exception: Error: -71112, Response: {"method": "searchVideoOfDay", "result": {}, "error_code": -71112}

Googled without success for python error -71112. What does this error mean?

**Comment by JurajNyiri** [comment]
It is error code from camera, these error codes are not documented anywhere.

**Comment by peakpeak-github** [comment]
I had the wrong date format. Now I'm getting this error with outputDir = "E:\\Dok\\Camerapics\\"
(E:\Dok\Camerapics exists and is empty)

Connecting to camera...
Getting recordings...

[WinError 2] The system cannot find the file specified
Warning: Could not calculate length from stream.
Downloading E:\Dok\Camerapics\2023-07-03 04_43_28-2023-07-03 04_46_20.mp4...
[WinError 2] The system cannot find the file specified
... looping the same over and over ...

**Comment by JurajNyiri** [comment]
Make sure E:\Dok\Camerapics\ exists.

**Comment by peakpeak-github** [comment]
Yes, the folder exists and is writable.

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/pytapo/issues/50

**Comment by peakpeak-github** [comment]
FFProbe was the missing part. Thanks!
