### ISSUE TITLE
requests.exceptions.SSLError

### ISSUE THREAD

**Issue by NicoCaldo** [JurajNyiri/pytapo#65]
I'm having an issue connecting to the camera.

Everything works fine on the app and I can stream the video with VLC and ping the IP. My credentials are correct and I've tried both my mail and `admin`

```
from pytapo import Tapo

user = "admin" # user you set in Advanced Settings -> Camera Account
password = "my_passowrd" # password you set in Advanced Settings -> Camera Account
host = "10.10.96.28" # ip of the camera, example: 192.168.1.52

tapo = Tapo(host, user, password)

print(tapo.getBasicInfo())
```

I'm having  `requests.exceptions.SSLError: HTTPSConnectionPool(host='10.10.96.28', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)')))`

I have 2FA ON, could it be the issue?

**Comment by NicoCaldo** [comment]
Seems to be an issue with Python 3.10 https://stackoverflow.com/questions/71006708/getting-sslv3-alert-handshake-failure-when-trying-to-connect-to-imap

**Comment by NicoCaldo** [comment]
A workaround is to `pip install requests "urllib3<2"` as explained [here](https://github.com/psf/requests/issues/6443) and then add `requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS += 'AES256-GCM-SHA384`' on top of `__init__.py`

Clearly, this solution needs urllib3 in a version that it's not the latest

**Comment by JurajNyiri** [comment]
Interestingly, this is not an issue when used within HA.

**Comment by JurajNyiri** [comment]
Fixed in pytapo==3.2.

**Comment by OrlandoStrike** [comment]
I use Python 3.11, having same issues, i just downgraded the library "urllib3" to 1.26, and now it works just fine.

![image](https://github.com/JurajNyiri/pytapo/assets/132246339/c8c6c02e-04a1-439a-b515-e2bee48f9011)

**Comment by efalk** [comment]
Seeing this with Python 3.12.1. I can probably provide a minimal test case if needed.

**Comment by Mitchell-kw-Lee** [comment]
Guys, there is a solution
at 
https://arista.my.site.com/AristaCommunity/s/article/Python-3-10-and-SSLV3-ALERT-HANDSHAKE-FAILURE-error
Which is really works.

**Comment by JurajNyiri** [comment]
This has been fixed since July 2023... Just update.

https://github.com/JurajNyiri/pytapo/issues/65#issuecomment-1656470805
