### ISSUE TITLE
Get error "-60102", cannot an error code definition, and need a workaround

### ISSUE THREAD

**Issue by Pajkastare** [JurajNyiri/pytapo#66]
I have used this code successfully with a pair of Tapo C200 cameras, but then I started to get the error "-60102". As an example:
```
>>> tapo.setPreset(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/pytapo/__init__.py", line 847, in setPreset
    return self.executeFunction(
  File "/usr/local/lib/python3.9/dist-packages/pytapo/__init__.py", line 138, in executeFunction
    raise Exception(
Exception: Error: -60102, Response: {"method": "motorMoveToPreset", "result": {}, "error_code": -60102}
```

**What does error code -60102 mean?**

I noticed this after implementing a firewall change to block the cameras from leaving my LAN. At the same time, I saw that my firewall blocked access to at least 5 different addresses of which at least 2 were Amazon EC2 nodes. It was TCP/443 (https) and UDP/123 (NTP). And the occasional UDP/53 (DNS). I might have missed something else.

This behaviour persisted even after rebooting the cameras. After the reboot, the time was wrong, 

The weird thing is that the cameras sometimes, not always (and sometimes after a long delay) actually did move as commanded. But mostly, they did not.

**Any workaround to get these cameras to work better without Internet connectivity?**

Also, I noticed there is a "getTime()" method but no "setTime()" method - So the NTP calls from the cameras might be the only way to update the time.

** ************************************************************************ **

**Edit: I had inadvertently allowed DNS traffic through my firewall, and that seemed to cause the timeouts and -60102 error codes. Also blocking DNS made the cameras responsive, without this error code.**

**The only remaining problem is that the video timestamp is wrong, since there does not seem to be any other way to set the time than to let the cameras query a public NTP server, and there is no "setTime()" method.**

**But the original issue is solved.**

** ************************************************************************ **

**Comment by Pajkastare** [comment]
Some more info: The commands from the python code seem to work, provided no other commands have been sent for a relatively long time. But issuing, for example, two different "motorMoveToPreset" commands in rapid succession usually fails for the second command.

Once, I had a camera change position about five (5!!) minutes after I sent the command.


From the looks of it, I'd say the cameras are trying to "phone home" and enter some sort of timeout if they can't reach the TPlink servers. It'd be nice to have a rapid response time even if they can't connect externally. 

Does anyone have a fix for this?

**Comment by Pajkastare** [comment]
The -60102 error seems to be due to a camera-internal timeout when it gets a valid IP address from a DNS query, but cannot access that external address. Workaround is to block DNS. Remaining problem is that the time does not seem to be able to be set without using NTP to external servers.

**Comment by JurajNyiri** [comment]
You can set the time using Onvif protocol locally.

**Comment by Pajkastare** [comment]
> You can set the time using Onvif protocol locally.
> 
> See [here](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/custom_components/tapo_control/utils.py#L1044C2-L1044C2).

Thanks for the info and link, I don't use Home assistant but I'll have a look.

I'll look into it when I get more free time on my hands, but I use these cameras with Zoneminder and I have not been able to get the Zoneminder ONVIF interface to work. I have not yet tested other Onvif software.
