### ISSUE TITLE
Repost for closing post #67

### ISSUE THREAD

**Issue by anmabi1984** [JurajNyiri/pytapo#68]
In reference of my previous #67 You might not believe but i bunched my head against Google the whole day long but without any success, it would had not be my purpose to wrote if I had found the solution.
PIP being an old version was not installed correctly could be fine, but no solution applied did solved it.
If you look for the specific error referred to MyTapo You will not find one single occurance on the Web.
If you look generally You will find a lot of occurency, but i tested all of them without any success.
Hope someone will be able to reply to this. 
PS: I reopened a new post since the last one was forcibly closed by the admin.
Regards
Andrea

**Comment by JurajNyiri** [comment]
Please refrain from opening new issues. Your issue is that your installation of pip cannot download any package, not just pytapo.

**Comment by anmabi1984** [comment]
You re wrong indeed
Other packages have been installed correctly prior and after the python upgrade.
Closing the topic could be useful for you, not for other people that may face the same issue in the future.
It would be good to share information other that simply punch off the people opening the topic and balimonf them for the reopening.
I dont get your behaviour.


Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JurajNyiri** [comment]
[No, I am not.](https://letmegooglethat.com/?q=WARNING%3A+pip+is+configured+with+locations+that+require+TLS%2FSSL%2C+however+the+ssl+module+in+Python+is+not+available.) 

Bonus points for including your env/os in the query.
