### ISSUE TITLE
RTP error

### ISSUE THREAD

**Issue by TiongTeck** [JurajNyiri/pytapo#69]
Hi, I tried use the DownloadRecordings.py but met with this error.
I am able to download 1 hour of recording before this error occurs.

This is the last line before the error
`Downloading F:\2023-07-25 16_00_00-2023-07-25 17_44_02.mp4: 4096.14 / 6242`

 ```
 File "C:\Users\UserName\AppData\Local\Programs\Python\pytapo\lib\site-packages\rtp\rtp.py", line 165, in sequenceNumber
    raise ValueError("SequenceNumber must be in range 0-2**16")
ValueError: SequenceNumber must be in range 0-2**16
```

**Comment by JurajNyiri** [comment]
How big are the individual recordings?

**Comment by TiongTeck** [comment]
Each file is slight more than 1 hour. It's 1 hour 6 minutes.

**Comment by JurajNyiri** [comment]
Can the recording length be changed to smaller chunks in the app? This script will not work with such a long periods.

**Comment by TiongTeck** [comment]
I am unable to change the recording length as I set it to continuous recording. I will change the recording mode to detection only for smaller chunks. Thanks!
