### ISSUE TITLE
 Compatibility with "Tapo C325WB"

### ISSUE THREAD

**Issue by HsiaoCH** [JurajNyiri/pytapo#71]
Hi there,
First of all, I want to express my heartfelt gratitude for your selfless contribution of the "pytapo" package to us.

I mainly want to inquire about the compatibility of the "pytapo" package with the latest "Tapo C325WB" camera. I am currently considering using this camera for a project.

If it's not compatible, I'd like to ask whether the "pytapo" package works with the "Tapo C320WS" or "Tapo C310" cameras.

If it is compatible, I'm curious whether the "pytapo" package supports the new AI features of the "Tapo C325WB" camera, such as obtaining detection coordinates for people and vehicles.

Your assistance is highly appreciated. Thank you!

**Comment by JurajNyiri** [comment]
Check https://github.com/JurajNyiri/HomeAssistant-Tapo-Control#troubleshooting--faq for verified working models.

It will most probably also work with C325WB and if not we will get it work. Let us know once you try it out!
