### ISSUE TITLE
Start/Stop recording

### ISSUE THREAD

**Issue by NicoCaldo** [JurajNyiri/pytapo#73]
I've a Tapo C210

Is there a way to start/stop recordingS that are saved on the SD?

**Comment by NicoCaldo** [comment]
No chance for this?

**Comment by JurajNyiri** [comment]
There are following functions for recording based on https://md.depau.eu/s/r1Ys_oWoP.

```
"getRecordPlan":                {"method":"get"},
    "setRecordPlan":                {"method":"set"},
    "getCircularRecordingConfig":   {"method":"get"},
    "setCircularRecordingConfig":   {"method":"set"},
```

They will need to be implemented first to modify recording behaviour.

**Comment by JurajNyiri** [comment]
getRecordPlan, setRecordPlan, getCircularRecordingConfig and setCircularRecordingConfig is now included in https://pypi.org/manage/project/pytapo/release/3.2.17/
