### ISSUE TITLE
Firmware Update damaged Login on C210 Camera. 

### ISSUE THREAD

**Issue by bask209** [JurajNyiri/pytapo#92]
Hello! 

My C210 autoupdated overnight and now I can't login using any method. 

Any of you have any ideas on how to fix it? 

I've tried admin and the old password I had. Also the one under advanced settings for the camera. It seems no permutation works for it, but my user and password works when I login on the camera. 

Any other ideas on how to login? Should I look for the older firmware and try and flash it back? 

Thanks!

**Comment by JurajNyiri** [comment]
Use the newest version and admin username along your tplink account password.
