### ISSUE TITLE
delete recordings from sd card

### ISSUE THREAD

**Issue by dwmurphy2** [JurajNyiri/pytapo#96]
sorry if I've missed something obvious, but I've been looking at some of the associated research/documentation and I don't see a way of deleting recordings ( downloading them ) from the sd card

I'm using a Tapo C425. Downloading works fine-ish ( tracking down some time zone issues ).

is this functionality known/available?
Thanks

**Comment by dwmurphy2** [comment]
My mistake - I just realized this functionality doesn't exist in the Tapo app either.  Maybe in the future....

**Comment by JurajNyiri** [comment]
Only formatting is available which is not ideal. Once this is added to the app we can add here as well.
