### ISSUE TITLE
method manual alarm not work

### ISSUE THREAD

**Issue by tiz001** [JurajNyiri/pytapo#97]
cam 520ws
firmware 1.2.5 build 231109 Rel 36811n

{
    "method": "do",
    "msg_alarm": {"manual_msg_alarm": {"action": "start"}},
}

Exception: Error: Parameter to get/do does not exist, Response: {"error_code": -40106}

I Tried with:
{
    "method": "get",
    "msg_alarm": {"manual_msg_alarm": {"action": "start"}},
}
Exception: Error: Function not supported, Response: {"error_code": -40210}

Thanks in advance

**Comment by JurajNyiri** [comment]
It does not work on all cameras unfortunately and there is no way to detect whether camera supports it or not.
