### ISSUE TITLE
No timeout in requests calls

### ISSUE THREAD

**Issue by eric2gif** [JurajNyiri/pytapo#99]
I have built a script that implements an MQTT client based on the pytapo (getEvents) method. The script keeps on interrogating my camera in search of a new event but also manages the MQTT keepalive with the broker. So it is essential that the getEvents interrogation is not locking the entire processing.
Unfortunately, I found that my camera has very unsteady response times (most of the time response in a few seconds but sometimes response time is greater than 30 seconds). The greatest response times cause my MQTT connection to break.
I have dig in the pytapo code and noticed that it makes calls to the "requests" package and that most of the requests class methods are able to handle a "timeout" parameter. BTW, I totally agree with what is written in the requests documentation "_Most requests to external servers should have a timeout attached, in case the server is not responding in a timely manner._".
I have tested a quick and dirty patch in the pytapo code:
![Pytapo_patch_timeout](https://github.com/JurajNyiri/pytapo/assets/153223050/cce2f4c2-74d8-495c-aa17-5aedbb3f9846)
Is it possible to have a clean implementation of the requests timeout in the pytapo package?

**Comment by JurajNyiri** [comment]
Not going to implement. Some cameras are slow and it is ok to wait for the response to come.
